### ISSUE TITLE
can i set face detector as id for the user like face recognition ?

### ISSUE THREAD

**Issue by robertyulisman** [nonam4/react-native-vision-camera-face-detector#10]
hay, this is not issue but i want to discuss, can i use this library to set face detection set like id so i save to database and give the name for the face, because i want to use for attendance app by detecting face

**Comment by nonam4** [comment]
I don't think I understand what you want to do...

You want to use detection result to work like an ID for a face? I don't think this is possible and if it does, I have no idea how you can achieve this with this package...
