### ISSUE TITLE
[QUESTION] detected half face ?

### ISSUE THREAD

**Issue by shinnobi** [nonam4/react-native-vision-camera-face-detector#17]

**Comment by shinnobi** [comment]
`if (camera.current) {
      // Lấy tọa độ trung tâm của khuôn mặt
      const faceCenterX = bounds.centerX;
      const faceCenterY = bounds.centerY;

      // Tính toán độ chênh lệch giữa tọa độ trung tâm của khuôn mặt và tọa độ trung tâm của camera
      const diffX = Math.abs(faceCenterX - cameraCenterX);
      const diffY = Math.abs(faceCenterY - cameraCenterY);

      // Kiểm tra xem khuôn mặt có ở giữa camera không
      if (diffX <= diff && diffY <= diff) {
        console.log("Khuôn mặt ở giữa camera");
        // Thực hiện hành động khi khuôn mặt ở giữa camera
      }
    }`
i use this code to detect  when the face is in center are of camera  but it not work, cameraCenterX alaways return 180 and faceCenterX is in range 0 to 1000 , can you please help me

**Comment by nonam4** [comment]
Take a look into example app. I know you'll manage how to achieve what you want using it 😁
