### ISSUE TITLE
Face always return empty object after upgrade vision camera to 4.0.0-beta.5

### ISSUE THREAD

**Issue by robertyulisman** [nonam4/react-native-vision-camera-face-detector#18]
hey @nonam4 i have some issue after upgrade vision camera, before i am using 3.9.1 but there is some bug like stretch previewing camera and other bug, but after upgrade to 4.0.0-beta.5 bug is solved but no face detected or return empty object on detect faces

![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/38e74a30-0893-48ab-9b96-4651a6ba1316)

but when i rotate the camera, the face is detected 
![WhatsApp Image 2024-03-22 at 11 55 49_3b81d7f5](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/63769e4a-bb43-42dd-b417-e7f75945e157)

when i change to normal position or potrait the face not detected 
![WhatsApp Image 2024-03-22 at 11 55 49_6e9d3007](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/9d5ebdcc-5cc5-4c5a-8dd5-98021eee0097)

 
i test on android 11 there is no problem, can you help for it ?

i am using react native vision camera react-native-vision-camera": "^4.0.0-beta.9
testing on android 10 xiaomy pocophone

**Comment by robertyulisman** [comment]
test on android 14 at redmi phone 
after update to react native vision camera react-native-vision-camera": "^4.0.0-beta.9

and using from example, the marker also not on the face place


https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/3142aa86-434b-4bf2-8b08-cac5281f0319

**Comment by nonam4** [comment]
I'll take a look into vision camera updates soon.
I'm currently working on another private project.

But you can try to fix it locally changing native code... I think this is something related to orientation in this line:
https://github.com/nonam4/react-native-vision-camera-face-detector/blob/d21a61f826c55aa4f43c99f941666704e5ac79ef/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.java#L243

try removing `fixedOrientation`variable and pass `orientation.toDegrees()` directly to `InputImage` and see if the error is solved

**Comment by robertyulisman** [comment]
i have update it @nonam4 , but the marker not on centered face, 

![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/284bcbc5-74e4-47f0-b547-190c6d37b3b7)


![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/5025044b-4c53-40c7-8d15-4464bbeac3a7)


![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/d202b8e3-4522-4fff-a85a-1a760e5b5532)

**Comment by robertyulisman** [comment]
i try too change on javascript file orientation in 'lanscape-right' from 270 to 360, but i dont think this will really fix for another device, 

![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/1215570a-5a6b-4135-9538-228ed25ee22d)



![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/9c46b291-4957-48b7-8b00-9f939066d4db)

![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/55675899/6b24e377-5b2e-4aeb-9b1d-d336127c92ca)

**Comment by nonam4** [comment]
@robertyulisman I'll take a look on this issue this week.
I was waiting to release a new version when vison camera releases a new non-beta version 😅

**Comment by nonam4** [comment]
@robertyulisman In my local tests the current code has fixed the original issue. 
Can you please provide me a feedback?

**Comment by robertyulisman** [comment]
sure @nonam4 i will check it, thanks for your help
