### ISSUE TITLE
[BUG] Plugin with id 'kotlin-android' not found.

### ISSUE THREAD

**Issue by YuriOlepir** [nonam4/react-native-vision-camera-face-detector#23]
Hi, I have failed Android build.
It says:
```
A problem occurred configuring project ':react-native-vision-camera-face-detector'.
> compileSdkVersion is not specified. Please add it to build.gradle
```
```
"react-native": "0.71.13",
"react-native-vision-camera": "^4.0.0-beta.12",
"react-native-vision-camera-face-detector": "^1.4.0",
"react-native-worklets-core": "^0.4.0",
 "react-native-reanimated": "3.6.2",
```
 
Error logs:

BUILD FAILED in 18s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installUftDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/yo/www/driver-app/node_modules/react-native-vision-camera-face-detector/android/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-vision-camera-face-detector'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

    at makeError (/Users/yo/www/driver-app/node_modules/execa/index.js:174:9)
    at /Users/yo/www/driver-app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/yo/www/driver-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/yo/www/driver-app/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

{
  "name": "driverApp",
  "version": "4.19.3",
  "private": true,
  "scripts": {},
  "dependencies": {
    "@mapbox/polyline": "^1.1.1",
    "@onfido/react-native-sdk": "10.7.0",
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/hooks": "^2.8.0",
    "@react-native-community/image-editor": "^2.3.0",
    "@react-native-community/netinfo": "^6.0.4",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-firebase/analytics": "^14.7.0",
    "@react-native-firebase/app": "^14.7.0",
    "@react-native-firebase/crashlytics": "^14.7.0",
    "@react-native-firebase/messaging": "^14.7.0",
    "@react-native-firebase/perf": "^14.7.0",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/compat": "^5.3.20",
    "@react-navigation/material-top-tabs": "^6.5.3",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "@react-navigation/stack": "^6.3.12",
    "@stripe/stripe-react-native": "0.35.1",
    "@types/mapbox__polyline": "^1.0.1",
    "@types/point-in-polygon": "^1.0.0",
    "axios": "^0.27.2",
    "clevertap-react-native": "^1.1.0",
    "code-push": "4.0.5",
    "dayjs": "^1.11.1",
    "deprecated-react-native-prop-types": "^4.1.0",
    "geolib": "^3.3.1",
    "humanize-duration": "^3.24.0",
    "i18next": "^19.8.1",
    "i18next-async-storage-backend2": "^2.0.3",
    "i18next-chained-backend": "^2.0.1",
    "i18next-http-backend": "^1.3.1",
    "jsc-android": "^241213.1.0",
    "libphonenumber-js": "^1.10.14",
    "lodash": "^4.17.20",
    "mobx": "^5.15.6",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^6.3.0",
    "moment": "^2.29.1",
    "moment-range": "^4.0.2",
    "moment-timezone": "^0.5.31",
    "patch-package": "^8.0.0",
    "point-in-polygon": "^1.0.1",
    "prop-types": "^15.7.2",
    "query-string": "^6.13.7",
    "react": "18.2.0",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.7.3",
    "react-lifecycles-compat": "^3.0.4",
    "react-native": "0.71.13",
    "react-native-alertbox": "^0.2.11",
    "react-native-base64": "0.1.0",
    "react-native-bluetooth-state-manager": "^1.3.2",
    "react-native-bootsplash": "^4.0.2",
    "react-native-calendar-events": "^2.2.0",
    "react-native-camera": "^4.2.1",
    "react-native-check-box": "^2.1.7",
    "react-native-circular-progress": "^1.3.6",
    "react-native-config": "^1.4.2",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-device-info": "^10.6.0",
    "react-native-document-picker": "^5.3.0",
    "react-native-exception-handler": "^2.10.9",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-hyperlink": "0.0.19",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-resizer": "^1.4.5",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-lightbox": "^0.8.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^1.4.3",
    "react-native-map-link": "^2.7.19",
    "react-native-maps": "1.9.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-markdown-display": "^6.1.6",
    "react-native-modal": "^13.0.1",
    "react-native-network-info": "^5.2.1",
    "react-native-offline": "^6.0.1",
    "react-native-pager-view": "^5.4.15",
    "react-native-paper": "^4.10.1",
    "react-native-permissions": "^4.0.0",
    "react-native-phone-call": "^1.0.9",
    "react-native-progress": "^5.0.0",
    "react-native-rate": "^1.2.4",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "3.6.2",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "3.29.0",
    "react-native-select-contact": "^1.5.0",
    "react-native-sensitive-info": "^5.5.8",
    "react-native-share": "10.0.2",
    "react-native-simple-crypto": "^0.2.15",
    "react-native-skeleton-placeholder": "^2.0.11",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-svg": "^13.4.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-tab-view": "^3.1.1",
    "react-native-toast-message": "^2.1.5",
    "react-native-touch-id": "^4.4.1",
    "react-native-vector-icons": "9.2.0",
    "react-native-video": "^5.2.0",
    "react-native-view-pdf": "^0.14.0",
    "react-native-vision-camera": "^4.0.0-beta.12",
    "react-native-vision-camera-face-detector": "^1.4.0",
    "react-native-webview": "^11.0.2",
    "react-native-worklets-core": "^0.4.0",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-decorators": "^7.10.5",
    "@babel/plugin-transform-runtime": "^7.11.5",
    "@babel/runtime": "^7.20.0",
    "@jumpn/react-native-jetifier": "^0.1.4",
    "@react-native-community/eslint-config": "^3.2.0",
    "@types/enzyme": "^3.10.14",
    "@types/humanize-duration": "^3.18.1",
    "@types/jest": "^27.5.1",
    "@types/lodash": "^4.14.161",
    "@types/moment-timezone": "^0.5.30",
    "@types/react": "^18.0.24",
    "@types/react-lifecycles-compat": "^3.0.1",
    "@types/react-native": "0.70.13",
    "@types/react-native-keyboard-spacer": "^0.4.3",
    "@types/react-native-permissions": "^2.0.0",
    "@types/react-native-share": "^3.3.4",
    "@types/react-native-tab-view": "^2.3.0",
    "@types/react-native-vector-icons": "^6.4.15",
    "@types/react-native-video": "^5.0.16",
    "@types/react-test-renderer": "^18.0.3",
    "@typescript-eslint/eslint-plugin": "5.53.0",
    "@typescript-eslint/eslint-plugin-tslint": "5.53.0",
    "@typescript-eslint/parser": "5.53.0",
    "babel-jest": "^27.5.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "chokidar-cli": "^2.1.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.5",
    "eslint": "^8.19.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jest": "27.2.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-react-native": "^3.11.0",
    "eslint-plugin-security": "^1.5.0",
    "eslint-plugin-standard": "^5.0.0",
    "husky": "^4.3.0",
    "jest": "^27.5.1",
    "jest-sonar": "^0.2.12",
    "license-checker": "^25.0.1",
    "lint-staged": "^10.4.0",
    "metro-react-native-babel-preset": "^0.76.9",
    "postinstall-postinstall": "^2.1.0",
    "react-native-clean-project": "^3.6.7",
    "react-native-svg-transformer": "^1.0.0",
    "react-test-renderer": "18.2.0",
    "reactotron-react-native": "5.0.3",
    "ts-jest": "^27.1.3",
    "tslint": "^6.1.3",
    "typescript": "4.9.4",
    "yarn-audit-fix": "^7.1.2"
  },
  "resolutions": {
    "@react-native/normalize-colors": "0.73.2",
    "react-native": "0.71.13"
  },
  "husky": {
    "hooks": {
      "pre-commit": "tsc && lint-staged"
    }
  },
  "lint-staged": {
    "*.{ts,tsx,js,jsx}": "eslint --max-warnings=100"
  }
}

**Comment by nonam4** [comment]
@YuriOlepir can you please check your app's `build.gradle` file if they have `kotlinVersion` and `compileSdkVersion` props defined?

**Comment by YuriOlepir** [comment]
Here is my build.gradle file, it seems that those defined
```

buildscript {

    ext {
        kotlinVersion = '1.8.0'
        buildToolsVersion = "33.0.0"
        minSdkVersion = 29
        compileSdkVersion = 34
        targetSdkVersion = 34
        googlePlayServicesVersion = "15+"
        androidMapsUtilsVersion = "0.5+"
        supportLibVersion = "29.0.0"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }

    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath 'com.google.firebase:perf-plugin:1.4.1'
        classpath 'com.facebook.react:react-native-gradle-plugin'
    }
}

def REACT_NATIVE_VERSION = new File(['node', '--print', "JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

...

```

**Comment by YuriOlepir** [comment]
@nonam4 I've just set up the new react-native project from the stretch with only these dependencies and got the same error.
```

"react-native": "0.71.13",
"react-native-vision-camera": "^4.0.0-beta.12",
"react-native-vision-camera-face-detector": "^1.4.0",
"react-native-worklets-core": "^0.4.0",
 "react-native-reanimated": "3.8.1",

```

**Comment by nonam4** [comment]
@YuriOlepir can you test new [build.gradle](https://github.com/nonam4/react-native-vision-camera-face-detector/blob/main/android/build.gradle) version and see if the error is gone?

**Comment by YuriOlepir** [comment]
> @YuriOlepir can you test new [build.gradle](https://github.com/nonam4/react-native-vision-camera-face-detector/blob/main/android/build.gradle) version and tell me if the error is gone?

I checked, there is nothing changed.

**Comment by nonam4** [comment]
Can you create a public repo with a min reproducible example?
So I'll be able to debug and fix this issue.

**Comment by namanh6669** [comment]
Same bug, can u update anything new? :(

**Comment by nonam4** [comment]
@namanh6669 does this error happens on example app?

**Comment by nonam4** [comment]
can you guys test new 1.4.1 version? Do it fix this issue?

**Comment by luanfvieira** [comment]
The issue persists in version 1.4.1

![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/8730936/16407e52-738e-4910-9f7b-9e8af0bf91a2)

**Comment by nonam4** [comment]
Please test new `1.4.2` version and give me a feedback about it 😁

**Comment by YuriOlepir** [comment]
> Please test new `1.4.2` version and give me a feedback about it 😁

Hi, I migrated from `v1.3.5` to the latest `v1.6.3`. 
this issue still exists.

I did a patch fix for the `node_modules/react-native-vision-camera-face-detector/android/build.gradle`, please check, maybe it will be helpful

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

def kotlinVersion = safeExtGet("VisionCameraFaceDetector_kotlinVersion", "1.9.20")

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:7.4.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    buildToolsVersion = safeExtGet("VisionCameraFaceDetector_buildToolsVersion", "34.0.0")
    ndkVersion safeExtGet("VisionCameraFaceDetector_ndkVersion", "25.1.8937393")

    defaultConfig {
        minSdkVersion safeExtGet("VisionCameraFaceDetector_minSdkVersion", 26)
        compileSdkVersion safeExtGet("VisionCameraFaceDetector_compileSdkVersion", 34)
        targetSdkVersion safeExtGet("VisionCameraFaceDetector_targetSdkVersion", 34)
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    lintOptions {
        disable "GradleCompatible"
    }
}

repositories {
    mavenLocal()
    maven {
        url("$rootDir/../node_modules/react-native/android")
    }

    google()
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${kotlinVersion}"
    implementation "com.facebook.react:react-native:+"
    api project(":react-native-vision-camera")
    implementation "androidx.annotation:annotation:1.7.1"
    implementation "androidx.camera:camera-core:1.3.3"
    implementation "com.google.mlkit:face-detection:16.1.6"
}


```

**Comment by luicfrr** [comment]
@YuriOlepir thanks for your help.
Can you open a PR with this fix?
