### ISSUE TITLE
[BUG] Downscaled face boundaries with lower photoResolution

### ISSUE THREAD

**Issue by imelos** [nonam4/react-native-vision-camera-face-detector#25]
When i use ```photoResolution``` ```'max'``` i receive correct face boundaries,
When i use ```1080 x 1920``` i receive downscaled face boundaries.
How can i adjust correct scaling preferably on android side?
Thank you!

Device Mi A2 Lite
react-native-vision-camera-face-detector 1.4.0

```
const cameraDevice = useCameraDevice('back');
const format = useCameraFormat(cameraDevice, [
  {photoResolution: {width: 1080, height: 1920}},
]);
```

**Comment by nonam4** [comment]
Please check if replacing `image.width/height` with `frame.width/height` in `scaleX/Y` definition (lines 249-253) solves this problem.

https://github.com/nonam4/react-native-vision-camera-face-detector/blob/fa88bd77f43aeade01f1e74e056c74f65d9db2b2/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.kt#L249

**Comment by imelos** [comment]
Thank you for fast answer!
I tried but nothing changed.

**Comment by nonam4** [comment]
Try adding some more logs about frame and image sizes, see if they change if you change `photoResolution`.

**Comment by imelos** [comment]
```frame``` and ```image``` have the same size despite of ```photoResolution``` changes. 
```1280x720``` in my case

**Comment by nonam4** [comment]
Well, in this case, I don't think this is possible to fix because the only sizes the plugin has access to come from the frame. If the frame doesn't reflect photoResolution, then I suppose there's nothing to be done 🤔

If you find a workaround please let me know so I can release a new version with this fix.

**Comment by nonam4** [comment]
@imelos Can you please check if [v1.5 branch](https://github.com/nonam4/react-native-vision-camera-face-detector/tree/v1.5) fix this issue as well?

**Comment by imelos** [comment]
@nonam4 with autoScale off in 1.5
when i set photoResolution to ```{photoResolution: {width: 1080, height: 1920}}``` face boundaries  look like square
when i dont set photo resolution face boundaries look like rectangle
not downscaled now
