### ISSUE TITLE
 camera mount error [unknown/unknown: [unknown/unknown] Compiling JS failed: 1:1:invalid empty parentheses '( )'

### ISSUE THREAD

**Issue by inayat0786** [nonam4/react-native-vision-camera-face-detector#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs and Screenshots**
If applicable, add logs and/or screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Vision Camera version [e.g. 1.0.0]
 - Face detector version [e.g. 1.0.0]

**Additional context**

**Comment by nonam4** [comment]
Minimum IOS required versio is 13.4. Closing as invalid issue
