### ISSUE TITLE
[BUG] Error when running build for Android

### ISSUE THREAD

**Issue by techmarajo** [nonam4/react-native-vision-camera-face-detector#29]
**Describe the bug**
When running the Android build, an error generated by Gradle occurs.

Error:
FAILURE: Build failed with an exception.
Build file '\node_modules\react-native-vision-camera-face-detector\android\build.gradle' line: 5
Could not find method safeExtGet() for arguments [kotlinVersion, 1.8.10] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.

**Expected behavior**
From what I've been reading, the scope of the "buildscript" is limited to the block itself, so it doesn't recognize the "safeExtGet" function.
To solve the issue, it was necessary to define the "kotlinVersion" variable globally, as this way, it's still possible to use the "safeExtGet" function.

**Logs and Screenshots**
Modified content:
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/116094322/ff0fc3c8-d0a3-4552-b11e-19b3d9d19331)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M34
 - OS: Android 14 (One UI 6)
 - Vision Camera version: ^3.9.2
 - Face detector version: ^1.4.1

**Comment by nonam4** [comment]
Thanks man, I really apretiate your help.
I think this is also related to #23

**Comment by nonam4** [comment]
Please test new `1.4.2` version and give me a feedback about it
