### ISSUE TITLE
(iOS): Doesn't build with expo modules

### ISSUE THREAD

**Issue by BalogunofAfrica** [nonam4/react-native-vision-camera-face-detector#3]
Great plugin!

I first got `could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator` when trying to build for iOS, error went away when I added `x86_64` to `Excluded Architecture`.

Now getting :
```shell
ld: building for 'iOS-simulator', but linking in object file (/path/to/project/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage[arm64][2](GMLImage.o)) built for 'iOS'
```
when I run on iOS. Builds fine for Android.

Here are my dependencies:

```json
{
    "expo": "^50.0.7",
    "react-native-vision-camera": "^3.9.0",
    "react-native-vision-camera-face-detector": "^1.2.2",
    "react-native-worklets-core": "^0.3.0",
}
```

Got the same result using `"expo": "50.0.4"` as suggested in the readme

**Comment by nonam4** [comment]
Are you using an expo managed workflow? (delete android/ios folders and let expo recreate them)

Also, are you using a M1 mac? 
If this is your case I think this is something related to [this](https://developers.google.com/ml-kit/known-issues#ios_issues) issue. Check [this](https://github.com/juliansteenbakker/mobile_scanner/issues/585) issue as there are some workarounds to try.

**Comment by nonam4** [comment]
Closing as stale
