### ISSUE TITLE
Pass detection options inside `initFrameProcessorPlugin`

### ISSUE THREAD

**Issue by nonam4** [nonam4/react-native-vision-camera-face-detector#32]
>Also btw; I really love your library it is crazy fast and works like a charm - but you should make use of the initializer.
>
> Instead of passing the options along on each call (`callback`), you can pass them to `initFrameProcessorPlugin` as a second argument, whichh passes thhem to the native plugin constructor.
>
> This is much more efficient.

_Originally posted by @mrousavy in https://github.com/nonam4/react-native-vision-camera-face-detector/issues/31#issuecomment-2057368107_

**Comment by mrousavy** [comment]
Ah nvm you already did it like that!
Nice work mate 💪

Btw I used your plugin for this demo: https://x.com/mrousavy/status/1779922031061917808?s=46&t=1cXOLI7mgsMcSjFIAruAkg

**Comment by nonam4** [comment]
I'm really happy to see my plugin in action, thanks 😁 
You got a new follower
