### ISSUE TITLE
[BUG] function '' cannot be shared error

### ISSUE THREAD

**Issue by Sachin1116** [nonam4/react-native-vision-camera-face-detector#38]
Frame Processor Error: Regular javascript function '' cannot be shared. Try decorating the function with the 'worklet' keyword to allow the javascript function to be used as a worklet., js engine: VisionCamera

**Comment by Nurmehemmed** [comment]
I am getting this error also

**Comment by Sachin1116** [comment]
its working I change in babel

module.exports = {
  presets: ["module:@react-native/babel-preset"],
  plugins: [
    ['react-native-reanimated/plugin', {
      processNestedWorklets: true
    }],
    ["react-native-worklets-core/plugin"]
  ]
};

**Comment by Nurmehemmed** [comment]
My babel config is also same 
module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    ['react-native-worklets-core/plugin'],
    [
      'react-native-reanimated/plugin',
      {
        processNestedWorklets: true,
      },
    ],
  ],
};
can u share please your Camera component?

**Comment by Sachin1116** [comment]
<Camera
        ref={camera}
        style={StyleSheet.absoluteFill}
        isActive={isCameraActive}
        device={cameraDevice}
        photo={true}
        // format={cameraFormat}
        onError={handleCameraMountError}
        faceDetectionCallback={handleFacesDetected}
        faceDetectionOptions={faceDetectionOptions}
      />

**Comment by Nurmehemmed** [comment]
how did you write **handleFacesDetected** component?

i wrote it like **const handleFacesDetectionn = Worklets.createRunOnJS(
    (faces: Face[], frame: Frame) => {**

**Comment by Sachin1116** [comment]
https://github.com/nonam4/react-native-vision-camera-face-detector/blob/main/example/src/index.tsx

**Comment by Nurmehemmed** [comment]
i wrote same as @nonam4 example but it throw same error still :(
 Frame Processor Error: Regular javascript function '' cannot be shared. Try decorating the function with the 'worklet' keyword to allow the javascript function 
to be used as a worklet., js engine: VisionCamera

**Comment by Nurmehemmed** [comment]
i am using bare workflow

**Comment by Sachin1116** [comment]
Getting error with Frame Processor Error: runOnJs(faces,frame).finally is not a function (it is undefined), js engine: VisionCamera


But when do changes in node modules react-native-vision-camera-face-detector camera.tsx its working fine. 

 const cameraFrameProcessor = useFrameProcessor( ( frame ) => {
    'worklet'
    runAsync( frame, async () => {
      'worklet'
      const internal = frame as FrameInternal
      const faces = detectFaces( frame )

      // increment frame count so we can use frame on 
      // js side without frame processor getting stuck
      internal.incrementRefCount()
      await runOnJs(
        faces,
        frame
      )
      // .finally( () => {
      //   // finally decrement frame count so it can be dropped
        internal.decrementRefCount()
      // } )
    } )
  }, [ runOnJs ] )

**Comment by Nurmehemmed** [comment]
There is some parameter that prevents this error for you. Maybe you have dedecting delay etc? But This happened for me and fixed after apply @Sachin1116 last change

**Comment by nonam4** [comment]
@Nurmehemmed Did you tested using example app?

**Comment by Nurmehemmed** [comment]
No i only test on my app but there is not something weird in my app. 
All dependencies versions are same with your example app. 
I tested on Samsung device when problem appear

**Comment by nonam4** [comment]
Can you please check if f555c39 fix the issue?

**Comment by Nurmehemmed** [comment]
Sorry, no

**Comment by Nurmehemmed** [comment]
@Sachin1116 change fix issue but maybe camera view is not smoothy anymore after that

**Comment by nonam4** [comment]
I can confirm that original problem was solved on 1.6.1 version as it's working on builded (also store published) apps.

**Comment by longb1997** [comment]
i still faced this with example in README
