### ISSUE TITLE
Plugin with id 'kotlin-android' not found.[BUG]

### ISSUE THREAD

**Issue by SantoshYadavSridix** [nonam4/react-native-vision-camera-face-detector#39]
**Describe the bug**
A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> Plugin with id 'kotlin-android' not found.

**Logs and Screenshots**
* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-vision-camera-face-detector'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Smartphone (please complete the following information):**
 - Vision Camera version: 4.0.1
 - react-native-vision-camera-face-detector: 1.4.0

**Additional context**
At the time of building project this error comes up.
![Screenshot 2024-04-23 at 2 03 05 PM](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/166494571/db32830d-9b02-4bff-a869-8f9ce3440404)

**Comment by nonam4** [comment]
You're using an outdated version of `react-native-vision-camera-face-detector`

**Comment by nolife08021** [comment]
@luicfrr  i facing same issue with V1.6.3

```
A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> Plugin with id 'kotlin-android' not found.
```

**Comment by luicfrr** [comment]
@nolife08021 can you reproduce this issue on example app?

**Comment by nolife08021** [comment]
@luicfrr not yet try, it it working with RN v0.71.17?
