### ISSUE TITLE
[FEAT] Is this available ?

### ISSUE THREAD

**Issue by TungE610** [nonam4/react-native-vision-camera-face-detector#41]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It would be nice if we have the option to [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, logs or screenshots about the feature request here.

**Comment by nonam4** [comment]
closing as invalid issue
