### ISSUE TITLE
Frame Processor: Not working when creating release build

### ISSUE THREAD

**Issue by SantoshYadavSridix** [nonam4/react-native-vision-camera-face-detector#48]
using react-native-vision-camera-face-detector: 1.6.0

**Comment by SantoshYadavSridix** [comment]
Okay, i will check and let you know.

**Comment by namnotfake** [comment]
> This problem fixed there already.

![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/147969833/a63c3209-cb28-4066-8c3e-3c01d77a29be)
"react-native-worklets-core": "^0.4.0",
"react-native-vision-camera-face-detector": "^1.6.1",
"react-native-vision-camera": "^4.0.0-beta.11",
"react-native-reanimated": "3.8.1",
I am configuring and getting the error as shown in the picture

**Comment by SantoshYadavSridix** [comment]
A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> Plugin with id 'kotlin-android' not found.

**Comment by SantoshYadavSridix** [comment]
> A problem occurred evaluating project ':react-native-vision-camera-face-detector'.
> 
> > Plugin with id 'kotlin-android' not found.


After adding below line in android/build.gradle

ext.kotlinVersion = "1.9.0"
classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")

Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by nonam4** [comment]
> @SantoshYadavSridix you can use 1.6.1 version. This problem fixed there already.

This is the sollution.
Closing as original problem was solved and new issues were opened with separated problems.
