### ISSUE TITLE
[Version 1.6.1 is notworking, need to new API]

### ISSUE THREAD

**Issue by namnotfake** [nonam4/react-native-vision-camera-face-detector#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs and Screenshots**
If applicable, add logs and/or screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Vision Camera version [e.g. 1.0.0]
 - Face detector version [e.g. 1.0.0]

**Additional context**

image
"react-native-worklets-core": "^0.4.0",
"react-native-vision-camera-face-detector": "^1.6.1",
"react-native-vision-camera": "^4.0.0-beta.11",
"react-native-reanimated": "3.8.1",
I am configuring and getting the error as shown in the picture

**Comment by namnotfake** [comment]
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/147969833/d5739f02-d205-4230-a190-83d36cc4b625)

**Comment by Nurmehemmed** [comment]
maybe it is cache error. Clear all caches and node modules again install it must works

**Comment by nonam4** [comment]
@namnotfake Delete `node_modules` folder then remove `^` from package's versions then reinstall all dependencies.

E.g: `"react-native-vision-camera-face-detector": "^1.6.1"` to `"react-native-vision-camera-face-detector": "1.6.1"`

Then do what @Nurmehemmed said.

**Comment by namnotfake** [comment]
> @namnotfake Delete `node_modules` folder then remove `^` from package's versions then reinstall all dependencies.
> 
> E.g: `"react-native-vision-camera-face-detector": "^1.6.1"` to `"react-native-vision-camera-face-detector": "1.6.1"`
> 
> Then do what @Nurmehemmed said.
I have a new problem here. Help me
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/147969833/4d8f3ad8-49c8-4a68-98a7-2211410c306c)

**Comment by namnotfake** [comment]
I did as you said and unfortunately a new problem arose

**Comment by luicfrr** [comment]
I just released 1.6.2 version 🥳🎉 It is using latest vision-camera and worklets-core and it's not crashing on release mode. Can you please test it and give me a feedback? Thanks

**Comment by namnotfake** [comment]
> I just released 1.6.2 version 🥳🎉 It is using latest vision-camera and worklets-core and it's not crashing on release mode. Can you please test it and give me a feedback? Thanks

Thank you, my problems have been solved. I found the reason from a few articles.
The problem was because I was using jdk21 and somehow it was not compatible with the expo and RN version I was using, I downgraded to jdk17 and everything was resolved. Could you add it to the README if anyone has the same problem.

**Comment by Mohamed-kassim** [comment]
> > I just released 1.6.2 version 🥳🎉 It is using latest vision-camera and worklets-core and it's not crashing on release mode. Can you please test it and give me a feedback? Thanks
> 
> Thank you, my problems have been solved. I found the reason from a few articles. The problem was because I was using jdk21 and somehow it was not compatible with the expo and RN version I was using, I downgraded to jdk17 and everything was resolved. Could you add it to the README if anyone has the same problem.

i have the same issue, unfortunately I have jdk version 17 any suggestions?
<img width="705" alt="Screenshot 2024-05-05 at 10 14 24 PM" src="https://github.com/luicfrr/react-native-vision-camera-face-detector/assets/37451755/447921b6-06f2-4014-ac11-2e40c61c0224">

**Comment by namnotfake** [comment]
> > > I just released 1.6.2 version 🥳🎉 It is using latest vision-camera and worklets-core and it's not crashing on release mode. Can you please test it and give me a feedback? Thanks
> > 
> > 
> > Thank you, my problems have been solved. I found the reason from a few articles. The problem was because I was using jdk21 and somehow it was not compatible with the expo and RN version I was using, I downgraded to jdk17 and everything was resolved. Could you add it to the README if anyone has the same problem.
> 
> i have the same issue, unfortunately I have jdk version 17 any suggestions? <img alt="Screenshot 2024-05-05 at 10 14 24 PM" width="705" src="https://private-user-images.githubusercontent.com/37451755/328042489-447921b6-06f2-4014-ac11-2e40c61c0224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzEzMjgsIm5iZiI6MTcxNDk3MTAyOCwicGF0aCI6Ii8zNzQ1MTc1NS8zMjgwNDI0ODktNDQ3OTIxYjYtMDZmMi00MDE0LWFjMTEtMmU0MGM2MWMwMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA0NTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMTQ5YjhlOGMzZjI4NmNhNzVhNmRlOTIxOWY5NmM5ZDUzZTFjNDMzZjZiZmQ2ZmI0MTEwN2FmZTlmZGQ4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iSqEt286UyD1r-bIep18k44kjdLu2wIGCU-sxD8jQYQ">

remove node-module, remove cache npm: npm cache clean --force. Before npm install, you must check package.json, remove "^" in package vision camera, camera detect face, worklets-core.
