### ISSUE TITLE
> @namnotfake Delete `node_modules` folder then remove `^` from package's versions then reinstall all dependencies.

### ISSUE THREAD

**Issue by namnotfake** [nonam4/react-native-vision-camera-face-detector#52]
> @namnotfake Delete `node_modules` folder then remove `^` from package's versions then reinstall all dependencies.
> 
> E.g: `"react-native-vision-camera-face-detector": "^1.6.1"` to `"react-native-vision-camera-face-detector": "1.6.1"`
> 
> Then do what @Nurmehemmed said.
I have a new problem here. Help me
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/147969833/4d8f3ad8-49c8-4a68-98a7-2211410c306c)

_Originally posted by @namnotfake in https://github.com/nonam4/react-native-vision-camera-face-detector/issues/49#issuecomment-2089547254_

**Comment by namnotfake** [comment]
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/147969833/d191cf6b-5e71-4f64-95f4-5ad9426a4d87)

**Comment by nonam4** [comment]
If you’re getting a `worklets-core` issue you should go to `worklets-core` repo. Stop spamming issues on my repo. This is your first warning. On seccond you'll be blocked.

**Comment by namnotfake** [comment]
> If you’re getting a `worklets-core` issue you should go to `worklets-core` repo. Stop spamming issues on my repo. This is your first warning. On seccond you'll be blocked.

Sorry. I don't spam and I'm actually having this problem. It's hard to understand that I'm the only one having it

**Comment by Nurmehemmed** [comment]
@namnotfake try to delete node modules and package-lock.json and npm i again. Then delete .gradle file in android folder and clear all caches finally try start start app again

**Comment by nonam4** [comment]
@namnotfake yes it seems you're the only having this issue. In my project it's working, on example app it's working, other people also get this working and all this makes me think you're not fully reading (or maybe missing a step) vision-camera/worklets-core's (and maybe my README's file) documentation. 

If you had created a good issue with all dependencies on your `package.json`, provided a minimum reproducible/example code, provided your `babel.config.js` file, etc... perhaps I could have helped you already, but as this wasn't the case so the only thing I can say is: This is not an issue with my plugin nor related to it so this is an invalid/spam issue.
