### ISSUE TITLE
npx expo run:ios gives could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by samsuchin** [nonam4/react-native-vision-camera-face-detector#53]
When I run 

`npx expo run:ios`

I get this error

`❌  (ios/Pods/Target Support Files/Pods-WinaBillion/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/samsuchin/Library/Developer/Xcode/DerivedData/WinaBillion-egnnxyuhythubkgnhdlwrdpsmfoo/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.framework/Modules/ExpoModulesCore.swiftmodule
   9 | import ExpoAdapterGoogleSignIn
  10 | import EXConstants
  11 | import ExpoCrypto

› 1 error(s), and 1 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.`

I have all the libraries installed, have my target os set to 14, and have done pod install successfully.

**Comment by nonam4** [comment]
This error is not related to my package.
