### ISSUE TITLE
smilingProbability not included

### ISSUE THREAD

**Issue by samsuchin** [nonam4/react-native-vision-camera-face-detector#54]
These are the only values returned when I detect a face. I've included classificationMode: "all", landmarkMode: "all", etc.

`faces [{"bounds": {"height": 953, "width": 953, "x": 219, "y": 559}, "pitchAngle": -2.633754253387451, "rollAngle": -71.53734588623047, "yawAngle": -22.85000228881836}] frame 1080 x 1920 yuv Frame`

**Comment by nonam4** [comment]
Yes, it IS returning `smilingProbability`. I’m using this value as one of the most important validations on my project.

Anyway, withou a minimum reproducible code I can’t reproduce this myself.
