### ISSUE TITLE
IOS: The facial recognition do not work as expected in release mode

### ISSUE THREAD

**Issue by tarikdev1** [nonam4/react-native-vision-camera-face-detector#6]
Hello,
the facial recognition work fine on debug mode, but do not work as expected on release mode

ENV :
```
     platform :ios, 13.4
    "react-native-reanimated": "^3.4.2",
    "react-native-vision-camera": "^3.9.0",
    "react-native-vision-camera-face-detector": "^1.2.3",
    "react-native": "0.72.3",
```

is there any special change should i put when i try to build the release version  ?

thanks

**Comment by nonam4** [comment]
What do you mean with "not working as expected"? 
What is happening with your app? 
Logs? 
Code?

**Comment by tarikdev1** [comment]
the faces list is empty ?

**Comment by nonam4** [comment]
Closing as stale
